#index:
#    path: /
#    controller: App\Controller\DefaultController::index
weather_in_cityy:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:cityAction

app_logout:
  path: /logout
  methods: GET